framework:
    cache:

        # Cache principal de l'application
        app: cache.adapter.redis

        # Connexion Redis (nom du container Docker)
        default_redis_provider: redis://redis:6379

        # Pools personnalisés
        pools:

            doctrine.system_cache_pool:
                adapter: cache.adapter.redis

            doctrine.result_cache_pool:
                adapter: cache.adapter.redis